image: node:10

cache:
  paths:
    - node_modules/

stages:
  - build
  - production

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      
server_listen:
  stage: production
  type: deploy
  script:
    - npm start
