image: node:10

cache:
  paths:
    - node_modules/

stages:
  - build
  - run

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    only:
      - dev
    except:
      - mast

server_listen:
  stage: run
  script:
    npm start
